import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ta" | "hi" | "te";

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    "app.title": "Missing Child – A Social Problem",
    "app.subtitle": "Protecting Children, Building Safer Communities",
    "common.back": "Back",
    "common.logout": "Logout",
    "common.submit": "Submit",
    "common.submitting": "Submitting...",
    "common.loading": "Loading...",
    "common.search": "Search...",
    "common.filter": "Filter",
    "common.all": "All",
    "common.name": "Name",
    "common.age": "Age",
    "common.gender": "Gender",
    "common.location": "Location",
    "common.status": "Status",
    "common.date": "Date",
    "common.details": "Details",
    "common.email": "Email",
    "common.password": "Password",
    "common.phone": "Phone",
    "common.address": "Address",
    "common.male": "Male",
    "common.female": "Female",
    "common.other": "Other",
    "common.missing": "Missing",
    "common.found": "Found",
    "common.language": "Language",
    "common.callPolice": "Call Police (100)",
    "common.callGuardian": "Call Guardian",
    "common.emergency": "Emergency Contacts",
    // Login
    "login.title": "Login",
    "login.noAccount": "Don't have an account?",
    "login.register": "Register",
    // Register
    "register.title": "Register",
    "register.as": "Register As",
    "register.parent": "Parent",
    "register.volunteer": "Volunteer",
    "register.fullName": "Full Name",
    "register.aadhar": "Aadhar Number",
    "register.haveAccount": "Already have an account?",
    // Dashboard
    "dashboard.parent": "Parent Dashboard",
    "dashboard.volunteer": "Volunteer Dashboard",
    "dashboard.admin": "Admin Dashboard",
    "dashboard.welcome": "Welcome",
    "dashboard.registerChild": "Register Child",
    "dashboard.yourChildren": "Your Registered Children",
    // Solutions
    "solution.rfid": "RFID Tracking",
    "solution.rfid.desc": "View child RFID details & school arrival tracking",
    "solution.smartid": "Smart ID",
    "solution.smartid.desc": "View child Smart ID with parent info",
    "solution.panic": "Panic Alert",
    "solution.panic.desc": "Send emergency panic alerts with location",
    "solution.community": "Community Awareness",
    "solution.community.desc": "Report missing/found children",
    // Panic
    "panic.title": "Panic Alert",
    "panic.childName": "Child Name",
    "panic.location": "Location",
    "panic.additionalDetails": "Additional Details",
    "panic.submit": "Submit Emergency Alert",
    "panic.detectLocation": "Detect my location",
    // Community
    "community.title": "Community Awareness Report",
    "community.reportType": "Report Type",
    "community.reportMissing": "Report Missing Child",
    "community.reportFound": "Report Found Child",
    "community.details": "Details",
    // Search & Filter
    "search.ageRange": "Age Range",
    "search.genderFilter": "Gender",
    "search.locationFilter": "Location",
    "search.sortBy": "Sort By",
    "search.newest": "Newest First",
    "search.oldest": "Oldest First",
    // Sighting
    "sighting.title": "Report a Sighting",
    "sighting.description": "Description",
    "sighting.uploadImage": "Upload Image",
    "sighting.linkCase": "Link to Case",
    "sighting.selectCase": "Select a case (optional)",
    // Case Status
    "case.missing": "Missing",
    "case.found": "Found",
    // OTP
    "otp.title": "OTP Verification",
    "otp.sent": "OTP sent to your registered number",
    "otp.enter": "Enter OTP",
    "otp.verify": "Verify OTP",
    "otp.resend": "Resend OTP",
    // Volunteer
    "volunteer.readOnly": "Read-only access",
    "volunteer.panicAlerts": "Panic Alerts",
    "volunteer.missingReports": "Missing Reports",
    "volunteer.childrenInfo": "Children Info",
    "volunteer.cannotEdit": "You cannot edit or delete any data",
    "volunteer.sensitiveHidden": "Sensitive parent information (Aadhar) is hidden for privacy",
    // Map
    "map.lastSeen": "Last Seen Location",
    "map.viewOnMap": "View on Map",
    // About
    "about.purpose": "This application helps prevent and respond to missing child cases using smart identification and emergency alert systems.",
    "about.warning": "Do not misuse the information in this system. All data is handled securely and ethically.",
    "about.continue": "I Understand — Continue",
    // Title page
    "title.getStarted": "Get Started",
    "title.hero": "Protecting Every Child. Empowering Every Community.",
    "title.desc": "A smart platform using RFID, Smart ID, Panic Alerts and Community Awareness to prevent and respond to missing child cases.",
  },
  ta: {
    "app.title": "காணாமல் போன குழந்தை – ஒரு சமூகப் பிரச்சினை",
    "app.subtitle": "குழந்தைகளைப் பாதுகாப்பது, பாதுகாப்பான சமூகங்களை உருவாக்குவது",
    "common.back": "பின்செல்",
    "common.logout": "வெளியேறு",
    "common.submit": "சமர்ப்பி",
    "common.submitting": "சமர்ப்பிக்கிறது...",
    "common.loading": "ஏற்றுகிறது...",
    "common.search": "தேடு...",
    "common.filter": "வடிகட்டு",
    "common.all": "அனைத்தும்",
    "common.name": "பெயர்",
    "common.age": "வயது",
    "common.gender": "பாலினம்",
    "common.location": "இடம்",
    "common.status": "நிலை",
    "common.date": "தேதி",
    "common.details": "விவரங்கள்",
    "common.email": "மின்னஞ்சல்",
    "common.password": "கடவுச்சொல்",
    "common.phone": "தொலைபேசி",
    "common.address": "முகவரி",
    "common.male": "ஆண்",
    "common.female": "பெண்",
    "common.other": "மற்றவை",
    "common.missing": "காணாமல்",
    "common.found": "கண்டுபிடிக்கப்பட்டது",
    "common.language": "மொழி",
    "common.callPolice": "காவல்துறையை அழை (100)",
    "common.callGuardian": "பாதுகாவலரை அழை",
    "common.emergency": "அவசர தொடர்புகள்",
    "login.title": "உள்நுழை",
    "login.noAccount": "கணக்கு இல்லையா?",
    "login.register": "பதிவு செய்",
    "register.title": "பதிவு",
    "register.as": "பதிவு செய்யும் வகை",
    "register.parent": "பெற்றோர்",
    "register.volunteer": "தன்னார்வலர்",
    "register.fullName": "முழுப் பெயர்",
    "register.aadhar": "ஆதார் எண்",
    "register.haveAccount": "ஏற்கனவே கணக்கு உள்ளதா?",
    "dashboard.parent": "பெற்றோர் டாஷ்போர்டு",
    "dashboard.volunteer": "தன்னார்வலர் டாஷ்போர்டு",
    "dashboard.admin": "நிர்வாக டாஷ்போர்டு",
    "dashboard.welcome": "வரவேற்கிறோம்",
    "dashboard.registerChild": "குழந்தையைப் பதிவு செய்",
    "dashboard.yourChildren": "பதிவு செய்யப்பட்ட குழந்தைகள்",
    "solution.rfid": "RFID கண்காணிப்பு",
    "solution.rfid.desc": "குழந்தை RFID விவரங்கள் மற்றும் பள்ளி வருகை",
    "solution.smartid": "ஸ்மார்ட் ஐடி",
    "solution.smartid.desc": "குழந்தை ஸ்மார்ட் ஐடி மற்றும் பெற்றோர் தகவல்",
    "solution.panic": "பீதி எச்சரிக்கை",
    "solution.panic.desc": "அவசர எச்சரிக்கைகளை அனுப்பு",
    "solution.community": "சமூக விழிப்புணர்வு",
    "solution.community.desc": "காணாமல்/கண்டுபிடிக்கப்பட்ட குழந்தைகளைப் புகாரளி",
    "panic.title": "பீதி எச்சரிக்கை",
    "panic.childName": "குழந்தையின் பெயர்",
    "panic.location": "இடம்",
    "panic.additionalDetails": "கூடுதல் விவரங்கள்",
    "panic.submit": "அவசர எச்சரிக்கையை சமர்ப்பி",
    "panic.detectLocation": "என் இருப்பிடத்தைக் கண்டறி",
    "community.title": "சமூக விழிப்புணர்வு புகார்",
    "community.reportType": "புகார் வகை",
    "community.reportMissing": "காணாமல் போன குழந்தையைப் புகாரளி",
    "community.reportFound": "கண்டுபிடிக்கப்பட்ட குழந்தையைப் புகாரளி",
    "community.details": "விவரங்கள்",
    "search.ageRange": "வயது வரம்பு",
    "search.genderFilter": "பாலினம்",
    "search.locationFilter": "இடம்",
    "search.sortBy": "வரிசைப்படுத்து",
    "search.newest": "புதியது முதலில்",
    "search.oldest": "பழையது முதலில்",
    "sighting.title": "ஒரு காட்சியைப் புகாரளி",
    "sighting.description": "விளக்கம்",
    "sighting.uploadImage": "படத்தைப் பதிவேற்று",
    "sighting.linkCase": "வழக்குடன் இணை",
    "sighting.selectCase": "ஒரு வழக்கைத் தேர்ந்தெடு (விருப்பம்)",
    "case.missing": "காணாமல்",
    "case.found": "கண்டுபிடிக்கப்பட்டது",
    "otp.title": "OTP சரிபார்ப்பு",
    "otp.sent": "உங்கள் பதிவு செய்த எண்ணுக்கு OTP அனுப்பப்பட்டது",
    "otp.enter": "OTP உள்ளிடு",
    "otp.verify": "OTP சரிபார்",
    "otp.resend": "OTP மீண்டும் அனுப்பு",
    "volunteer.readOnly": "படிக்க மட்டும் அணுகல்",
    "volunteer.panicAlerts": "பீதி எச்சரிக்கைகள்",
    "volunteer.missingReports": "காணாமல் போன புகார்கள்",
    "volunteer.childrenInfo": "குழந்தை தகவல்",
    "volunteer.cannotEdit": "நீங்கள் எந்த தரவையும் திருத்த அல்லது நீக்க முடியாது",
    "volunteer.sensitiveHidden": "தனியுரிமைக்காக முக்கிய பெற்றோர் தகவல்கள் மறைக்கப்பட்டுள்ளன",
    "map.lastSeen": "கடைசியாக பார்த்த இடம்",
    "map.viewOnMap": "வரைபடத்தில் காண்",
    "about.purpose": "இந்த செயலி காணாமல் போன குழந்தை வழக்குகளைத் தடுக்கவும் பதிலளிக்கவும் உதவுகிறது.",
    "about.warning": "இந்த அமைப்பில் உள்ள தகவல்களை தவறாகப் பயன்படுத்தாதீர்கள்.",
    "about.continue": "புரிகிறது — தொடரவும்",
    "title.getStarted": "தொடங்கு",
    "title.hero": "ஒவ்வொரு குழந்தையும் பாதுகாக்கப்படும். ஒவ்வொரு சமூகமும் வலுப்படுத்தப்படும்.",
    "title.desc": "RFID, ஸ்மார்ட் ஐடி, பீதி எச்சரிக்கைகள் மற்றும் சமூக விழிப்புணர்வைப் பயன்படுத்தும் ஒரு ஸ்மார்ட் தளம்.",
  },
  hi: {
    "app.title": "लापता बच्चा – एक सामाजिक समस्या",
    "app.subtitle": "बच्चों की रक्षा, सुरक्षित समुदायों का निर्माण",
    "common.back": "वापस",
    "common.logout": "लॉगआउट",
    "common.submit": "जमा करें",
    "common.submitting": "जमा हो रहा है...",
    "common.loading": "लोड हो रहा है...",
    "common.search": "खोजें...",
    "common.filter": "फ़िल्टर",
    "common.all": "सभी",
    "common.name": "नाम",
    "common.age": "उम्र",
    "common.gender": "लिंग",
    "common.location": "स्थान",
    "common.status": "स्थिति",
    "common.date": "तारीख",
    "common.details": "विवरण",
    "common.email": "ईमेल",
    "common.password": "पासवर्ड",
    "common.phone": "फ़ोन",
    "common.address": "पता",
    "common.male": "पुरुष",
    "common.female": "महिला",
    "common.other": "अन्य",
    "common.missing": "लापता",
    "common.found": "मिला",
    "common.language": "भाषा",
    "common.callPolice": "पुलिस को कॉल करें (100)",
    "common.callGuardian": "अभिभावक को कॉल करें",
    "common.emergency": "आपातकालीन संपर्क",
    "login.title": "लॉगिन",
    "login.noAccount": "खाता नहीं है?",
    "login.register": "पंजीकरण",
    "register.title": "पंजीकरण",
    "register.as": "के रूप में पंजीकरण",
    "register.parent": "माता-पिता",
    "register.volunteer": "स्वयंसेवक",
    "register.fullName": "पूरा नाम",
    "register.aadhar": "आधार संख्या",
    "register.haveAccount": "पहले से खाता है?",
    "dashboard.parent": "माता-पिता डैशबोर्ड",
    "dashboard.volunteer": "स्वयंसेवक डैशबोर्ड",
    "dashboard.admin": "व्यवस्थापक डैशबोर्ड",
    "dashboard.welcome": "स्वागत है",
    "dashboard.registerChild": "बच्चा पंजीकरण",
    "dashboard.yourChildren": "पंजीकृत बच्चे",
    "solution.rfid": "RFID ट्रैकिंग",
    "solution.rfid.desc": "बच्चे के RFID विवरण और स्कूल आगमन",
    "solution.smartid": "स्मार्ट आईडी",
    "solution.smartid.desc": "बच्चे की स्मार्ट आईडी और माता-पिता की जानकारी",
    "solution.panic": "पैनिक अलर्ट",
    "solution.panic.desc": "आपातकालीन अलर्ट भेजें",
    "solution.community": "सामुदायिक जागरूकता",
    "solution.community.desc": "लापता/पाए गए बच्चों की रिपोर्ट करें",
    "panic.title": "पैनिक अलर्ट",
    "panic.childName": "बच्चे का नाम",
    "panic.location": "स्थान",
    "panic.additionalDetails": "अतिरिक्त विवरण",
    "panic.submit": "आपातकालीन अलर्ट भेजें",
    "panic.detectLocation": "मेरा स्थान पता लगाएं",
    "community.title": "सामुदायिक जागरूकता रिपोर्ट",
    "community.reportType": "रिपोर्ट प्रकार",
    "community.reportMissing": "लापता बच्चे की रिपोर्ट करें",
    "community.reportFound": "पाए गए बच्चे की रिपोर्ट करें",
    "community.details": "विवरण",
    "search.ageRange": "उम्र सीमा",
    "search.genderFilter": "लिंग",
    "search.locationFilter": "स्थान",
    "search.sortBy": "क्रम",
    "search.newest": "नवीनतम पहले",
    "search.oldest": "पुराना पहले",
    "sighting.title": "एक दृश्य की रिपोर्ट करें",
    "sighting.description": "विवरण",
    "sighting.uploadImage": "छवि अपलोड करें",
    "sighting.linkCase": "केस से जोड़ें",
    "sighting.selectCase": "एक केस चुनें (वैकल्पिक)",
    "case.missing": "लापता",
    "case.found": "मिला",
    "otp.title": "OTP सत्यापन",
    "otp.sent": "आपके पंजीकृत नंबर पर OTP भेजा गया",
    "otp.enter": "OTP दर्ज करें",
    "otp.verify": "OTP सत्यापित करें",
    "otp.resend": "OTP फिर भेजें",
    "volunteer.readOnly": "केवल पढ़ने की पहुँच",
    "volunteer.panicAlerts": "पैनिक अलर्ट",
    "volunteer.missingReports": "लापता रिपोर्ट",
    "volunteer.childrenInfo": "बच्चों की जानकारी",
    "volunteer.cannotEdit": "आप कोई भी डेटा संपादित या हटा नहीं सकते",
    "volunteer.sensitiveHidden": "गोपनीयता के लिए संवेदनशील माता-पिता की जानकारी छिपाई गई है",
    "map.lastSeen": "अंतिम बार देखा गया स्थान",
    "map.viewOnMap": "मानचित्र पर देखें",
    "about.purpose": "यह एप्लिकेशन लापता बच्चों के मामलों को रोकने और उनका जवाब देने में मदद करता है।",
    "about.warning": "इस प्रणाली की जानकारी का दुरुपयोग न करें।",
    "about.continue": "समझ गया — जारी रखें",
    "title.getStarted": "शुरू करें",
    "title.hero": "हर बच्चे की रक्षा। हर समुदाय को सशक्त बनाना।",
    "title.desc": "RFID, स्मार्ट आईडी, पैनिक अलर्ट और सामुदायिक जागरूकता का उपयोग करने वाला एक स्मार्ट प्लेटफॉर्म।",
  },
  te: {
    "app.title": "తప్పిపోయిన పిల్లల – ఒక సామాజిక సమస్య",
    "app.subtitle": "పిల్లలను రక్షించడం, సురక్షితమైన సమాజాలను నిర్మించడం",
    "common.back": "వెనుకకు",
    "common.logout": "లాగ్ అవుట్",
    "common.submit": "సమర్పించు",
    "common.submitting": "సమర్పిస్తోంది...",
    "common.loading": "లోడ్ అవుతోంది...",
    "common.search": "వెతకండి...",
    "common.filter": "ఫిల్టర్",
    "common.all": "అన్నీ",
    "common.name": "పేరు",
    "common.age": "వయసు",
    "common.gender": "లింగం",
    "common.location": "ప్రదేశం",
    "common.status": "స్థితి",
    "common.date": "తేదీ",
    "common.details": "వివరాలు",
    "common.email": "ఇమెయిల్",
    "common.password": "పాస్‌వర్డ్",
    "common.phone": "ఫోన్",
    "common.address": "చిరునామా",
    "common.male": "పురుషుడు",
    "common.female": "స్త్రీ",
    "common.other": "ఇతర",
    "common.missing": "తప్పిపోయిన",
    "common.found": "కనుగొన్న",
    "common.language": "భాష",
    "common.callPolice": "పోలీసులకు కాల్ చేయండి (100)",
    "common.callGuardian": "సంరక్షకుడికి కాల్ చేయండి",
    "common.emergency": "ఎమర్జెన్సీ సంప్రదింపులు",
    "login.title": "లాగిన్",
    "login.noAccount": "ఖాతా లేదా?",
    "login.register": "నమోదు",
    "register.title": "నమోదు",
    "register.as": "గా నమోదు",
    "register.parent": "తల్లిదండ్రి",
    "register.volunteer": "వాలంటీర్",
    "register.fullName": "పూర్తి పేరు",
    "register.aadhar": "ఆధార్ నంబర్",
    "register.haveAccount": "ఇప్పటికే ఖాతా ఉందా?",
    "dashboard.parent": "తల్లిదండ్రి డాష్‌బోర్డ్",
    "dashboard.volunteer": "వాలంటీర్ డాష్‌బోర్డ్",
    "dashboard.admin": "అడ్మిన్ డాష్‌బోర్డ్",
    "dashboard.welcome": "స్వాగతం",
    "dashboard.registerChild": "పిల్లలను నమోదు చేయండి",
    "dashboard.yourChildren": "నమోదు చేయబడిన పిల్లలు",
    "solution.rfid": "RFID ట్రాకింగ్",
    "solution.rfid.desc": "పిల్లల RFID వివరాలు మరియు పాఠశాల రాక",
    "solution.smartid": "స్మార్ట్ ఐడి",
    "solution.smartid.desc": "పిల్లల స్మార్ట్ ఐడి మరియు తల్లిదండ్రుల సమాచారం",
    "solution.panic": "పానిక్ అలర్ట్",
    "solution.panic.desc": "ఎమర్జెన్సీ అలర్ట్‌లను పంపండి",
    "solution.community": "సమాజ అవగాహన",
    "solution.community.desc": "తప్పిపోయిన/కనుగొన్న పిల్లలను రిపోర్ట్ చేయండి",
    "panic.title": "పానిక్ అలర్ట్",
    "panic.childName": "పిల్లల పేరు",
    "panic.location": "ప్రదేశం",
    "panic.additionalDetails": "అదనపు వివరాలు",
    "panic.submit": "ఎమర్జెన్సీ అలర్ట్ సమర్పించు",
    "panic.detectLocation": "నా స్థానాన్ని గుర్తించు",
    "community.title": "సమాజ అవగాహన నివేదిక",
    "community.reportType": "నివేదిక రకం",
    "community.reportMissing": "తప్పిపోయిన పిల్లలను రిపోర్ట్ చేయండి",
    "community.reportFound": "కనుగొన్న పిల్లలను రిపోర్ట్ చేయండి",
    "community.details": "వివరాలు",
    "search.ageRange": "వయసు పరిధి",
    "search.genderFilter": "లింగం",
    "search.locationFilter": "ప్రదేశం",
    "search.sortBy": "క్రమం",
    "search.newest": "కొత్తది ముందు",
    "search.oldest": "పాతది ముందు",
    "sighting.title": "దృశ్యాన్ని రిపోర్ట్ చేయండి",
    "sighting.description": "వివరణ",
    "sighting.uploadImage": "చిత్రాన్ని అప్‌లోడ్ చేయండి",
    "sighting.linkCase": "కేసుకు లింక్ చేయండి",
    "sighting.selectCase": "కేసును ఎంచుకోండి (ఐచ్ఛికం)",
    "case.missing": "తప్పిపోయిన",
    "case.found": "కనుగొన్న",
    "otp.title": "OTP ధృవీకరణ",
    "otp.sent": "మీ నమోదు చేసిన నంబర్‌కు OTP పంపబడింది",
    "otp.enter": "OTP నమోదు చేయండి",
    "otp.verify": "OTP ధృవీకరించు",
    "otp.resend": "OTP మళ్ళీ పంపు",
    "volunteer.readOnly": "చదవడం మాత్రమే యాక్సెస్",
    "volunteer.panicAlerts": "పానిక్ అలర్ట్‌లు",
    "volunteer.missingReports": "తప్పిపోయిన నివేదికలు",
    "volunteer.childrenInfo": "పిల్లల సమాచారం",
    "volunteer.cannotEdit": "మీరు ఏ డేటాను సవరించడం లేదా తొలగించడం చేయలేరు",
    "volunteer.sensitiveHidden": "గోప్యత కోసం సున్నితమైన తల్లిదండ్రుల సమాచారం దాచబడింది",
    "map.lastSeen": "చివరిగా చూసిన ప్రదేశం",
    "map.viewOnMap": "మ్యాప్‌లో చూడండి",
    "about.purpose": "ఈ అప్లికేషన్ తప్పిపోయిన పిల్లల కేసులను నివారించడానికి మరియు ప్రతిస్పందించడానికి సహాయపడుతుంది.",
    "about.warning": "ఈ వ్యవస్థలోని సమాచారాన్ని దుర్వినియోగం చేయకండి.",
    "about.continue": "అర్థమైంది — కొనసాగించు",
    "title.getStarted": "ప్రారంభించు",
    "title.hero": "ప్రతి పిల్లవాడిని రక్షించడం. ప్రతి సమాజాన్ని శక్తివంతం చేయడం.",
    "title.desc": "RFID, స్మార్ట్ ఐడి, పానిక్ అలర్ట్‌లు మరియు సమాజ అవగాహనను ఉపయోగించే స్మార్ట్ ప్లాట్‌ఫారమ్.",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  ta: "தமிழ்",
  hi: "हिन्दी",
  te: "తెలుగు",
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languageNames: Record<Language, string>;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  languageNames,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageNames }}>
      {children}
    </LanguageContext.Provider>
  );
};
